# Generated by Django 2.0.13 on 2019-11-29 11:41

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('nsitf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_Status',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employers',
            name='local_council',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', null=True, on_delete=django.db.models.deletion.CASCADE, to='nsitf.Local_Government'),
        ),
    ]
