# Generated by Django 2.0.13 on 2019-11-29 12:06

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('nsitf', '0002_auto_20191129_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employers',
            old_name='date_registered',
            new_name='CAC_reg_date',
        ),
        migrations.AddField(
            model_name='employers',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nsitf.Registration_Status'),
        ),
        migrations.AlterField(
            model_name='employers',
            name='branch',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='nsitf.Branches'),
        ),
    ]
