# Generated by Django 2.0.13 on 2019-11-29 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsitf', '0003_auto_20191129_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='status',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nsitf.Registration_Status'),
        ),
    ]
