# Generated by Django 2.0.13 on 2019-12-02 10:57

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('nsitf', '0004_auto_20191129_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAC_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cac_no', models.IntegerField()),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('Reg_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='employers',
            old_name='phone',
            new_name='Telephone1',
        ),
        migrations.RenameField(
            model_name='employers',
            old_name='address1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employers',
            old_name='name',
            new_name='employer_name',
        ),
        migrations.RemoveField(
            model_name='employers',
            name='entred_by',
        ),
        migrations.AddField(
            model_name='employers',
            name='Telephone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employers',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='employers',
            name='postal_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nsitf.Branches'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nsitf.Regions'),
        ),
        migrations.AlterField(
            model_name='employers',
            name='branch',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, to='nsitf.Branches'),
        ),
    ]
