# Generated by Django 2.0.13 on 2019-12-05 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsitf', '0006_auto_20191203_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStaff',
            fields=[
                ('staff_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_Entry_staff', models.BooleanField(default=False)),
                ('is_Approval_manager', models.BooleanField(default=False)),
                ('is_Sys_admin', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nsitf.Branches')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nsitf.Regions')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nsitf.State')),
            ],
        ),
    ]
