# Generated by Django 2.0.13 on 2019-12-06 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsitf', '0007_allstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='cancelled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employers',
            name='last_changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employers',
            name='last_changed_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employers',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
