# Generated by Django 2.0.13 on 2019-12-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsitf', '0012_auto_20191215_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.IntegerField(max_length=150, null=True),
        ),
    ]
