# Generated by Django 2.0.13 on 2019-12-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsitf', '0013_auto_20191217_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employers',
            name='employer_code',
        ),
        migrations.AddField(
            model_name='employers',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
