# Generated by Django 2.0.13 on 2019-12-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsitf', '0014_auto_20191217_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='employer_numb',
        ),
    ]
