# Generated by Django 2.0.13 on 2019-12-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsitf', '0015_remove_employees_employer_numb'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employer_numb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nsitf.Employers'),
        ),
    ]
