# Generated by Django 2.0.13 on 2019-12-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsitf', '0017_auto_20191219_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_tasks',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nsitf.Employers'),
        ),
    ]
